name: Portfolio CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check HTML
        run: |
          test -f index.html
          echo "✅ index.html found"

      - name: Check CSS
        run: |
          test -f style.css
          echo "✅ style.css found"

      - name: Check JavaScript
        run: |
          test -f script.js
          echo "✅ script.js found"

      - name: Check Profile Photo
        run: |
          test -f WhatsApp Image 2024-01-10 at 14.54.17_8528658b.jpg
          echo "✅ WhatsApp Image 2024-01-10 at 14.54.17_8528658b.jpg found"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS S3
        run: |
          aws s3 sync . s3://protfolio-second --delete

      - name: Deployment successful
        run: |
          echo "🚀 Portfolio deployed successfully!"
